TEST_MODE: 3
log_dir: "models/expt_b"
ckpt_path: "model.ckpt"
UPDATE: True
SCALE: 1
PENALTY: 0 
VIZ: False
NUM_CPU: 2
BATCH_SIZE: 1
NPCS: 15
CKPT_FREQ: 64
LOAD_CKPT: null
NUM_STEPS: 100000
EPISODE_LEN: 6
SINGLE_CAM: False
MESH: False
PORT: 2034
TM_PORT: 8034
RESCALE_REWARD: False
REWARD_MAX: 1.0
LR: 4e-4
